// ---------------------------------------------------------------------------
// Verification domain types — data structures for AI-powered code verification.
//
// Covers five interconnected verification layers:
// 1. Adversarial Tests — property-based tests generated from the diff
// 2. Contracts — inferred preconditions/postconditions/invariants
// 3. Behavioral Delta — what behaviors changed vs. were preserved
// 4. CI Bridge — execution via GitLab CI or local sandbox
// 5. Trust Calibration — confidence scoring for verification results
//
// Design decisions:
// - Each layer has its own data types but they compose into a single
//   VerificationData container for the store and cache.
// - All IDs are simple strings (same as ReviewComment, EdgeCase, etc.).
// - Results are per-file where applicable (tests, contracts) and per-MR
//   where applicable (behavioral delta, trust).
// - The CI bridge types are execution-agnostic — they describe what to
//   run and what came back, not how it was run.
// - Trust scores are always present (computed client-side from AI reasoning
//   when no server/CI is available, or from real execution metrics when
//   a runner is configured).
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 1. Adversarial Tests — "Break It"
// ---------------------------------------------------------------------------

/**
 * A single property-based test generated by the AI.
 * Targets a specific function in the diff.
 */
export type PropertyTest = {
  id: string;
  property: string;            // Human-readable property description
  testCode: string;            // Runnable test code (TypeScript/fast-check style)
  targetFunction: string;      // Function name being tested
  filePath: string;            // File containing the function
  lineRange: { start: number; end: number } | null;
};

/**
 * Result of running a single property test.
 * When no runner is available, the AI provides a reasoned assessment.
 */
export type PropertyTestResult = {
  testId: string;
  status: 'held' | 'counterexample' | 'error' | 'not-run';
  iterations: number | null;   // How many inputs were tried (null if AI-reasoned)
  counterexample: string | null; // Minimal failing input, if found
  errorMessage: string | null;
  aiReasoned: boolean;         // true if result came from AI reasoning, not execution
};

/**
 * All adversarial test data for a single file.
 */
export type FileTestData = {
  filePath: string;
  tests: PropertyTest[];
  results: PropertyTestResult[];
};

/**
 * Top-level container for all adversarial test data across the MR.
 */
export type AdversarialTestData = {
  files: FileTestData[];
  totalTests: number;
  totalHeld: number;
  totalCounterexamples: number;
  totalErrors: number;
};

// ---------------------------------------------------------------------------
// 2. Contracts — "Prove the Boundaries"
// ---------------------------------------------------------------------------

/**
 * A single contract statement (precondition, postcondition, or invariant).
 */
export type ContractStatement = {
  human: string;               // Plain English description
  code: string | null;         // TypeScript assertion / Zod schema (null if not expressible)
};

/**
 * Inferred contracts for a single function.
 */
export type FunctionContract = {
  id: string;
  functionName: string;
  filePath: string;
  lineRange: { start: number; end: number } | null;
  preconditions: ContractStatement[];
  postconditions: ContractStatement[];
  invariants: ContractStatement[];
  verificationStatus: 'verified' | 'violation-possible' | 'unknown';
  violationPath: string | null;  // Description of how the contract can be violated
  aiReasoned: boolean;           // true if verified by AI reasoning, not execution
};

/**
 * Top-level container for all contract data across the MR.
 */
export type ContractData = {
  contracts: FunctionContract[];
  totalVerified: number;
  totalViolations: number;
  totalUnknown: number;
};

// ---------------------------------------------------------------------------
// 3. Behavioral Delta — "What Actually Changed?"
// ---------------------------------------------------------------------------

export type BehaviorChangeType = 'changed' | 'preserved' | 'unexpected';

/**
 * A single behavior identified in the diff.
 */
export type BehaviorEntry = {
  id: string;
  description: string;         // Human-readable behavior description
  type: BehaviorChangeType;
  testScenario: string;        // Description of how to verify this behavior
  expectedOutcome: string;     // What should happen
  actualOutcome: string | null; // What actually happened (null if not executed)
  filePaths: string[];         // Files involved in this behavior
  verified: boolean;           // Whether this was verified by execution
  aiReasoned: boolean;         // true if verified by AI reasoning, not execution
};

/**
 * Top-level container for behavioral delta analysis.
 */
export type BehavioralDeltaData = {
  changed: BehaviorEntry[];
  preserved: BehaviorEntry[];
  unexpected: BehaviorEntry[];
  summary: string;             // One-line overview of the behavioral delta
};

// ---------------------------------------------------------------------------
// 4. CI Bridge — execution layer
// ---------------------------------------------------------------------------

export type CiExecutionMethod = 'gitlab-ci' | 'server' | 'local' | 'ai-only';

export type CiJobStatus = 'pending' | 'running' | 'success' | 'failed' | 'cancelled';

/**
 * Tracks a CI verification job triggered by Otto.
 */
export type CiVerificationJob = {
  method: CiExecutionMethod;
  pipelineId: number | null;   // GitLab pipeline ID (null for non-CI methods)
  pipelineUrl: string | null;  // Link to the pipeline in GitLab
  jobStatus: CiJobStatus;
  startedAt: number;           // timestamp
  completedAt: number | null;
};

/**
 * Results returned from a CI/server execution run.
 * Maps back to the test/contract/behavior IDs for correlation.
 */
export type CiExecutionResult = {
  job: CiVerificationJob;
  testResults: PropertyTestResult[];
  mutationScore: number | null;       // 0-1, from mutation testing
  coverageDelta: number | null;       // 0-1, branch coverage improvement
  executionTimeMs: number;
};

// ---------------------------------------------------------------------------
// 5. Trust Calibration — "Don't Trust, Verify the Verifier"
// ---------------------------------------------------------------------------

export type TrustLevel = 'high' | 'medium' | 'low';

/**
 * Individual trust signals that compose into the overall score.
 */
export type TrustSignals = {
  mutationScore: number | null;       // 0-1: % of mutants killed
  coverageDelta: number | null;       // 0-1: new branch coverage
  counterexampleQuality: number;      // 0-1: how minimal/reproducible
  testIndependence: number;           // 0-1: tests pass in isolation
  nonTautological: number;            // 0-1: tests assert meaningful things
};

/**
 * Trust assessment for a verification result.
 * Attached to every file-level or MR-level verification output.
 */
export type TrustAssessment = {
  level: TrustLevel;
  score: number;               // 0-100 composite score
  signals: TrustSignals;
  explanation: string;         // Human-readable summary of why this score
  survivingMutants: string[];  // Descriptions of mutations that weren't caught
  canStrengthen: boolean;      // Whether re-generation could improve the score
};

// ---------------------------------------------------------------------------
// Composite — the single container stored in the review store and cache.
// ---------------------------------------------------------------------------

export type VerificationStatus = 'idle' | 'generating' | 'executing' | 'complete' | 'error';

/**
 * Top-level verification data for the entire MR.
 * This is what the store holds and the cache persists.
 */
export type VerificationData = {
  status: VerificationStatus;
  error: string | null;

  // Layer outputs
  adversarialTests: AdversarialTestData | null;
  contracts: ContractData | null;
  behavioralDelta: BehavioralDeltaData | null;

  // Execution
  execution: CiExecutionResult | null;
  executionMethod: CiExecutionMethod;

  // Trust
  trust: TrustAssessment | null;

  // Timestamps
  generatedAt: number | null;
  executedAt: number | null;
};

/**
 * Initial empty state for the verification data.
 */
export const EMPTY_VERIFICATION_DATA: VerificationData = {
  status: 'idle',
  error: null,
  adversarialTests: null,
  contracts: null,
  behavioralDelta: null,
  execution: null,
  executionMethod: 'ai-only',
  trust: null,
  generatedAt: null,
  executedAt: null,
};
